it:
  languageName: Italiano
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Consiglio Generale degli Studenti – Università degli Studi dell'Insubria – [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "CGS @uninsubria"
  description: "Consiglio Generale degli Studenti dell'Università degli Studi dell'Insubria"
  params:
    ### accessibility ###
    # accessibility:
    #   skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/example-page/"
    ### calls to action ###
    # main_cta:
    #   text: "Join"
    #   link: "/example-page/"
    # footer_cta:
    #   text: "Join us"
    #   link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "il-CGS"
      name: "Il CGS"
      url: "/il-CGS/"
      weight: 1
    - identifier: "chi-siamo"
      name: "Chi siamo"
      url: "/chi-siamo/"
      weight: 1
      post: ""
      parent: "il-CGS"
    - identifier: "statuto"
      name: "Statuto del CGS"
      url: "/statuto/"
      weight: 2
      post: ""
      parent: "il-CGS"
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
    # - identifier: "child-3"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 3
    #   post: "Nulla consequat massa quis enim. Donec pede justo."
    #   parent: "about"
    # - identifier: "example"
    #   name: "Example"
    #   url: "/example-page/"
    #   weight: 2
    # - identifier: "example-1"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 1
    #   post: "Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo."
    #   parent: "example"
    # - identifier: "example-2"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 2
    #   post: "Nulla consequat massa quis enim. Donec pede justo."
    #   parent: "example"
    # - identifier: "example-3"
    #   name: "Example Child Page"
    #   url: "/example-page/"
    #   weight: 3
    #   post: "Aenean commodo ligula get dolor. Aenean massa. "
    #   parent: "example"
    # - identifier: "demo-page"
    #   name: "Demo Page"
    #   url: "/demo-page/"
    #   weight: 3
    # - identifier: "faq"
    #   name: "FAQs"
    #   url: "/faq/"
    #   weight: 4
    # - identifier: "blog"
    #   name: "Blog"
    #   url: "/blog/"
    #   weight: 5
# es:
#   languageName: Spanish
#   contentDir: content/es
#   weight: 2
#   title: "Título del Sitio"
#   description: "Descripción del Sitio"
#   menu:
#     main:
#     - identifier: "about"
#       name: "Acerca de"
#       url: "/example-page/"
#       weight: 1
#     - identifier: "child-1"
#       name: "Página Hija de Ejemplo"
#       url: "/example-page/"
#       weight: 1
#       parent: "about"
#     - identifier: "faq"
#       name: "FAQs"
#       url: "/faq/"
#       weight: 3
#     - identifier: "blog"
#       name: "Blog"
#       url: "/blog/"
#       weight: 2
